/**
 * Location Constants
 * Countries and US States for dropdown selectors
 */

export const US_STATES = [
  { value: '', label: 'Select State' },
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'District of Columbia' },
  { value: 'PR', label: 'Puerto Rico' }
] as const

export const COUNTRIES = [
  { value: '', label: 'Select Country' },
  { value: 'USA', label: 'United States' },
  { value: 'CAN', label: 'Canada' },
  { value: 'MEX', label: 'Mexico' },
  { value: 'GBR', label: 'United Kingdom' },
  { value: 'IRL', label: 'Ireland' },
  { value: 'AUS', label: 'Australia' },
  { value: 'NZL', label: 'New Zealand' },
  { value: 'DEU', label: 'Germany' },
  { value: 'FRA', label: 'France' },
  { value: 'ESP', label: 'Spain' },
  { value: 'ITA', label: 'Italy' },
  { value: 'NLD', label: 'Netherlands' },
  { value: 'BEL', label: 'Belgium' },
  { value: 'CHE', label: 'Switzerland' },
  { value: 'AUT', label: 'Austria' },
  { value: 'SWE', label: 'Sweden' },
  { value: 'NOR', label: 'Norway' },
  { value: 'DNK', label: 'Denmark' },
  { value: 'FIN', label: 'Finland' },
  { value: 'POL', label: 'Poland' },
  { value: 'CZE', label: 'Czech Republic' },
  { value: 'HUN', label: 'Hungary' },
  { value: 'ROU', label: 'Romania' },
  { value: 'BGR', label: 'Bulgaria' },
  { value: 'GRC', label: 'Greece' },
  { value: 'PRT', label: 'Portugal' },
  { value: 'BRA', label: 'Brazil' },
  { value: 'ARG', label: 'Argentina' },
  { value: 'CHL', label: 'Chile' },
  { value: 'COL', label: 'Colombia' },
  { value: 'PER', label: 'Peru' },
  { value: 'VEN', label: 'Venezuela' },
  { value: 'ECU', label: 'Ecuador' },
  { value: 'URY', label: 'Uruguay' },
  { value: 'PRY', label: 'Paraguay' },
  { value: 'BOL', label: 'Bolivia' },
  { value: 'CRI', label: 'Costa Rica' },
  { value: 'PAN', label: 'Panama' },
  { value: 'GTM', label: 'Guatemala' },
  { value: 'SLV', label: 'El Salvador' },
  { value: 'HND', label: 'Honduras' },
  { value: 'NIC', label: 'Nicaragua' },
  { value: 'DOM', label: 'Dominican Republic' },
  { value: 'CHN', label: 'China' },
  { value: 'JPN', label: 'Japan' },
  { value: 'KOR', label: 'South Korea' },
  { value: 'IND', label: 'India' },
  { value: 'SGP', label: 'Singapore' },
  { value: 'HKG', label: 'Hong Kong' },
  { value: 'TWN', label: 'Taiwan' },
  { value: 'THA', label: 'Thailand' },
  { value: 'MYS', label: 'Malaysia' },
  { value: 'IDN', label: 'Indonesia' },
  { value: 'PHL', label: 'Philippines' },
  { value: 'VNM', label: 'Vietnam' },
  { value: 'PAK', label: 'Pakistan' },
  { value: 'BGD', label: 'Bangladesh' },
  { value: 'LKA', label: 'Sri Lanka' },
  { value: 'ZAF', label: 'South Africa' },
  { value: 'EGY', label: 'Egypt' },
  { value: 'NGA', label: 'Nigeria' },
  { value: 'KEN', label: 'Kenya' },
  { value: 'MAR', label: 'Morocco' },
  { value: 'TUN', label: 'Tunisia' },
  { value: 'DZA', label: 'Algeria' },
  { value: 'GHA', label: 'Ghana' },
  { value: 'ARE', label: 'United Arab Emirates' },
  { value: 'SAU', label: 'Saudi Arabia' },
  { value: 'QAT', label: 'Qatar' },
  { value: 'KWT', label: 'Kuwait' },
  { value: 'BHR', label: 'Bahrain' },
  { value: 'OMN', label: 'Oman' },
  { value: 'ISR', label: 'Israel' },
  { value: 'TUR', label: 'Turkey' },
  { value: 'RUS', label: 'Russia' },
  { value: 'UKR', label: 'Ukraine' },
  { value: 'OTHER', label: 'Other' }
] as const

export type USState = typeof US_STATES[number]['value']
export type Country = typeof COUNTRIES[number]['value']
